language: go

go:
    - 1.5

install:
    - go get -u github.com/golang/lint/golint
    - go get -u github.com/GeertJohan/fgt

script:
    - make && make check
    - fgt gofmt -l $(find src -name \*.go)
    #- fgt golint src/...
    # The simple form above does not work anymore, since we need to
    # skip src/internal.
    - fgt find src -type d \( -name internal -prune -o -exec golint {} \; \)
